version: '3.9'

services:
  userservice:
    build: ./userservice
    container_name: userservice
    ports:
      - 5000:5000
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
  krakend_ce:
    image: devopsfaith/krakend:1.3.0
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"